version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tickets
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./seedermongo.js:/docker-entrypoint-initdb.d/seedermongo.js:ro
    environment:
      - MONGO_INITDB_DATABASE=tickets

volumes:
  mongo-data:
